#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/Applications/Racket v7.1/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-I' 'scheme/init' '-qt-' '/Users/Dood/Desktop/School/Current/CSCI3508 Software/Connect Four - CSCI 3508 3/connect-four-naive.rkt'  ${1+"$@"}
